name: CI - Testes Automatizados

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 18
      
      - run:  npm install 

      - name: Executar testes do Cypress
        run: npx cypress run